# Image for serving NGINX with all its static
# All right reserved PT. SUMBER MAKMUR SURYA PERKASA

FROM nginx:1.22.1-alpine

COPY ./nginx-app-release.conf /etc/nginx/conf.d/default.conf
COPY ./nginx.conf /etc/nginx/nginx.conf
